version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=gary
      - POSTGRES_PASSWORD=SuperSecretPW!
      - POSTGRES_DB=radnet
    volumes:
      - postgres:/var/lib/postrgresql/data
    ports:
    - '5432:5432'
volumes:
  postgres:
